/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fr.nicopico.kotlinpoet

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.PrintStream
import kotlin.io.path.Path

fun main() {
    val packageName = "fr.nicopico.kotlinpoet"
    val rxStubClassName = ClassName(packageName, "RxStub")
    val rxStubName = "rxStub"

    val fileSpec = FileSpec.builder(packageName, "CoroutineStub")
        .addType(
            TypeSpec.classBuilder("CoroutineStub")
                .primaryConstructor(
                    FunSpec.constructorBuilder()
                        .addParameter(
                            ParameterSpec
                                .builder(rxStubName, rxStubClassName)
                                .build()
                        )
                        .build()
                )
                .addProperty(
                    PropertySpec
                        .builder(rxStubName, rxStubClassName)
                        .initializer(rxStubName)
                        .build()
                )
                .addFunctions(generateFunSpecs(rxStubName, RxStub::class.methods))
                .build()
        )
        .build()

    println(fileSpec.toString())
}
